services:
  sqlserver:
    container_name: sisenterprise
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      SA_PASSWORD: "Jdt7$uwF9u^B8uvd"
      ACCEPT_EULA: "Y"
      MSSQL_PID: "Developer"
    ports:
      - "1433:1433"
  mssqltools:
    container_name: sisenterprise-tools
    image: mcr.microsoft.com/mssql-tools
    depends_on:
      - sqlserver
    volumes:
      - ./volume/sisenterprise_produção.sql:/tmp/sisenterprise_produção.sql
      - ./volume/init-sisenterprise_produção.sh:/tmp/init-sisenterprise_produção.sh
    command: /bin/bash ./tmp/init-sisenterprise_produção.sh